"""JSON Schemas for batchalign worker/batch IPC protocols."""

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["**/*"], exclude = ["BUILD.bazel"]),
)

filegroup(
    name = "batch_items",
    srcs = glob(["batch_items/**/*"]),
)

filegroup(
    name = "worker_v2",
    srcs = glob(["worker_v2/**/*"]),
)
