"""Wire-protocol Python types for every batchalign worker boundary.

This module is the **stable public name** that backends import from. It
re-exports every generated pydantic-v2 type from the sibling
`_proto_generated` module (autogenerated from the Rust schemars output via
the Bazel `_proto_generated` genrule) and contributes the hand-written
rehydration helpers that bridge Rust serde's tagged-enum JSON to typed
Python instances.

Source of truth: `crates/batchalign/batchalign-core/src/proto/*.rs` plus
the `TaskInput` / `TaskOutput` unions in `base.rs`. To change a field,
edit the Rust file and rebuild — the next `bazel build` regenerates the
Python side. There is no `just gen-proto` recipe and no manual codegen
step; if `_proto_generated.py` is missing, the Bazel py_library wiring is
broken (or you ran `maturin develop` without the Bazel-staged copy).

Why a shim and not regenerate-into-this-file: the rehydration helpers
(`rebuild_tagged_inputs`, `serialize_tagged_outputs`) are called by the
Rust-side `BackendImpl::call` over JSON and need to live somewhere the
generator never overwrites.
"""

from __future__ import annotations

from typing import Any

# Re-export every generated type. The generated module is the single
# canonical source for the class set; `__all__` is computed from its
# public names so adding/removing a Rust proto type propagates here
# automatically on the next Bazel build.
from batchalign._core._proto_generated import (  # noqa: F401
    # Shared
    LanguageSpecAuto,
    LanguageSpecCode,
    LanguageSpecPerFile,
    PreparedAudio,
    # ASR
    AsrInput,
    AsrOptions,
    AsrOutput,
    AsrSegment,
    AsrWord,
    # Forced alignment
    FaInput,
    FaOutput,
    # Speaker diarization
    Diarization,
    DiarizationSegment,
    SpeakerInput,
    SpeakerOutput,
    # Utterance segmentation
    UtSegInput,
    UtSegOutput,
    UtteranceSpan,
    # Morphosyntax
    MorphosyntaxInput,
    MorphosyntaxOutput,
    MorphosyntaxToken,
    MorphosyntaxUtterance,
    TaggedUtterance,
    # Translate
    TranslateInput,
    TranslateOutput,
    # Coref
    CorefInput,
    CorefOutput,
    # openSMILE
    OpenSmileInput,
    OpenSmileOutput,
    # AVQI
    AvqiInput,
    AvqiOutput,
    # Compare
    CompareInput,
    CompareMetrics,
    CompareMetricsPos,
    CompareOutput,
    # Tagged unions
    TaskInput,
    TaskOutput,
    # Per-variant union members (TaskInputAsr, TaskOutputAsr, …) are
    # available on `_proto_generated` for advanced uses but not normally
    # imported here — backends only need the input/output classes.
)

# `LanguageSpec` is the discriminated-union alias most backends want. The
# generated module emits one BaseModel per variant; expose a tuple alias so
# `isinstance(spec, LanguageSpec)` works ergonomically.
LanguageSpec = (LanguageSpecAuto, LanguageSpecCode, LanguageSpecPerFile)


# ---------------------------------------------------------------------------
# Tagged-dict → typed pydantic rehydration.
#
# The Rust engine ships a serde-JSON encoding of `Vec<TaskInput>` (each item
# tagged `{"task": "<Variant>", "data": {...}}`) across the PyO3 boundary;
# we reconstitute each item to its typed proto class here so backend
# `call()` methods see a real `MorphosyntaxInput` (with a real
# `LanguageSpecAuto` nested) instead of plain dicts. The inverse helper
# serializes a backend's typed `*Output` instances back to that same
# tagged-dict shape for the round-trip.
# ---------------------------------------------------------------------------

# Tag → input dataclass. Tag values are the Rust enum variant names from
# `crates/batchalign/batchalign-core/src/base.rs::TaskInput` and must stay
# in lockstep with serde's `#[serde(tag = "task", content = "data")]`
# encoding. The generated `TaskInput` discriminated union enforces the same
# mapping; this table exists separately because `rebuild_tagged_inputs`
# receives one item at a time, not a wrapped list.
_TAG_TO_INPUT: dict[str, type] = {
    "Asr": AsrInput,
    "Fa": FaInput,
    "Speaker": SpeakerInput,
    "UtSeg": UtSegInput,
    "Morphosyntax": MorphosyntaxInput,
    "Translate": TranslateInput,
    "Coref": CorefInput,
    "OpenSmile": OpenSmileInput,
    "Avqi": AvqiInput,
    "Compare": CompareInput,
}

_OUTPUT_TO_TAG: dict[type, str] = {
    AsrOutput: "Asr",
    FaOutput: "Fa",
    SpeakerOutput: "Speaker",
    UtSegOutput: "UtSeg",
    MorphosyntaxOutput: "Morphosyntax",
    TranslateOutput: "Translate",
    CorefOutput: "Coref",
    OpenSmileOutput: "OpenSmile",
    AvqiOutput: "Avqi",
    CompareOutput: "Compare",
}


def rebuild_tagged_inputs(items: list[dict]) -> list[Any]:
    """Convert a list of `{"task": tag, "data": {...}}` dicts (as produced
    by Rust serde's `TaskInput` tagged-enum serialisation) into typed proto
    pydantic instances ready to feed a Python `Backend.call()`."""
    out: list[Any] = []
    for item in items:
        tag = item.get("task")
        cls = _TAG_TO_INPUT.get(tag)
        if cls is None:
            raise TypeError(f"unknown TaskInput tag {tag!r}")
        out.append(cls.model_validate(item.get("data", {})))
    return out


def serialize_tagged_outputs(items: list[Any]) -> list[dict]:
    """Inverse of `rebuild_tagged_inputs`: take a list of typed `*Output`
    pydantic instances and emit the tagged-dict shape Rust serde expects on
    the way back. `model_dump(mode='json')` matches what `serde_json`
    parses on the Rust side — bytes round-trip as base64 strings, etc."""
    out: list[dict] = []
    for item in items:
        tag = _OUTPUT_TO_TAG.get(type(item))
        if tag is None:
            raise TypeError(f"unknown Output type {type(item).__name__}")
        out.append({"task": tag, "data": item.model_dump(mode="json")})
    return out
