"""Round-trip smoke tests for the autogenerated proto module.

Exercises the path that crosses the PyO3 boundary in `BackendImpl::call`:

  Rust serde JSON → `rebuild_tagged_inputs` → typed pydantic model
                                            → backend.call(...)
                                            → typed pydantic *Output
       `serialize_tagged_outputs` → JSON → Rust serde

The test does not load the Rust extension; it just verifies that the
Python types produced by the Bazel codegen agree with the on-wire shape
that `crates/batchalign/batchalign-engine/src/backend_impl.rs` emits.
"""

from __future__ import annotations

import base64

import numpy as np
import pytest


def test_proto_module_imports() -> None:
    """The shim re-exports every name backends rely on."""
    from batchalign._core import proto as p

    for name in [
        "AsrInput",
        "AsrOutput",
        "AsrSegment",
        "AsrWord",
        "AsrOptions",
        "PreparedAudio",
        "LanguageSpecAuto",
        "LanguageSpecCode",
        "LanguageSpecPerFile",
        "FaInput",
        "FaOutput",
        "SpeakerInput",
        "SpeakerOutput",
        "DiarizationSegment",
        "Diarization",
        "UtSegInput",
        "UtSegOutput",
        "UtteranceSpan",
        "MorphosyntaxInput",
        "MorphosyntaxOutput",
        "MorphosyntaxToken",
        "TranslateInput",
        "TranslateOutput",
        "CorefInput",
        "CorefOutput",
        "CompareInput",
        "CompareOutput",
        "CompareMetrics",
        "TaskInput",
        "TaskOutput",
        "rebuild_tagged_inputs",
        "serialize_tagged_outputs",
    ]:
        assert hasattr(p, name), f"missing proto name: {name}"


def test_prepared_audio_pcm_is_bytes() -> None:
    """Wire arrives as base64 string; pydantic auto-decodes to `bytes` so
    `np.frombuffer(audio.pcm_f32le, …)` keeps working on the backend side."""
    from batchalign._core.proto import PreparedAudio

    payload = b"\x00\x00\x80?" * 4  # four float32 ones
    b64 = base64.b64encode(payload).decode()
    audio = PreparedAudio(
        pcm_f32le=b64, sample_rate=16000, channels=1, frame_count=4
    )
    assert isinstance(audio.pcm_f32le, bytes)
    arr = np.frombuffer(audio.pcm_f32le, dtype=np.float32)
    assert tuple(arr) == (1.0, 1.0, 1.0, 1.0)


def test_rebuild_tagged_inputs_dispatches_by_task() -> None:
    """`rebuild_tagged_inputs` maps the Rust serde `{task, data}` envelope
    to the right typed pydantic model."""
    from batchalign._core.proto import (
        AsrInput,
        MorphosyntaxInput,
        rebuild_tagged_inputs,
    )

    b64 = base64.b64encode(b"\x00" * 16).decode()
    items = [
        {
            "task": "Asr",
            "data": {
                "source_id": "fileA",
                "audio": {
                    "pcm_f32le": b64,
                    "sample_rate": 16000,
                    "channels": 1,
                    "frame_count": 4,
                },
                "language": {"kind": "auto"},
                "options": {},
            },
        },
        {
            "task": "Morphosyntax",
            "data": {
                "source_id": "fileA",
                "utterance_id": 0,
                "language": {"kind": "code", "value": "eng"},
                "tokens": ["hello", "world"],
                "retokenize": False,
                "text": "hello world",
            },
        },
    ]
    out = rebuild_tagged_inputs(items)
    assert isinstance(out[0], AsrInput)
    assert isinstance(out[1], MorphosyntaxInput)
    assert out[0].source_id == "fileA"
    assert out[1].tokens == ["hello", "world"]
    # LanguageSpec discriminator survived the round-trip.
    assert out[1].language.kind == "code"
    assert out[1].language.value == "eng"


def test_serialize_tagged_outputs_round_trips_with_rust_shape() -> None:
    """The output envelope must match what Rust serde deserializes:
    `[{"task": "<Variant>", "data": {...}}]`."""
    from batchalign._core.proto import (
        AsrOutput,
        AsrSegment,
        AsrWord,
        TranslateOutput,
        serialize_tagged_outputs,
    )

    asr = AsrOutput(
        source_id="fileA",
        segments=[
            AsrSegment(
                start_ms=0,
                end_ms=100,
                text="hi",
                speaker=None,
                words=[AsrWord(text="hi", start_ms=0, end_ms=100, confidence=0.9)],
            )
        ],
    )
    translate = TranslateOutput(source_id="fileA", utterances=["hola"])
    payload = serialize_tagged_outputs([asr, translate])

    assert payload[0]["task"] == "Asr"
    assert payload[0]["data"]["source_id"] == "fileA"
    assert payload[0]["data"]["segments"][0]["words"][0]["text"] == "hi"
    assert payload[1]["task"] == "Translate"
    assert payload[1]["data"]["utterances"] == ["hola"]


def test_unknown_tag_rejected() -> None:
    """The rehydrator refuses unknown task tags rather than silently
    dropping work."""
    from batchalign._core.proto import rebuild_tagged_inputs

    with pytest.raises(TypeError, match="unknown TaskInput tag"):
        rebuild_tagged_inputs([{"task": "Nonexistent", "data": {}}])
